import { EmpréstimoConsignadoValues } from "../Types";

export const initialValuesForm: EmpréstimoConsignadoValues = {
  beneficio: "",
  nome: "",
  dataNascimento: "",
  cpf: "",
  situacaoBeneficio: "",
  nit: "",
  identidade: 0,
  sexo: "",
  dib: "",
  valorBeneficio: 1,
  possuiRepresentanteLegalProcurador: "Não",
  pensaoAlimenticia: "Não",
  bloqueioEmprestismo: "Não",
  beneficioPermiteEmprestimo: "Sim",
  naoPerturbe: "",
  rg: "",
  ddb: "",
  nomeMae: "",
  descontosCartao: {},
  enderecoPessoal: {
    bairro: "N/D",
    cep: "N/D",
    cidade: "N/D",
    endereco: "N/D",
    uf: "N/D",
  },
  especie: {
    codigo: "",
    descricao: "",
  },
  margem: {
    competencia: "",
    baseCalculoMargemConsignavel: 0,
    margemDisponivelEmprestimo: 0,
    margemDisponivelCartao: 0,
    percentualMargemDisponivelEmprestimo: 0,
    percentualMargemTotalEmprestimo: 0,
    quantidadeEmprestimo: 0,
    possuiCartao: "Sim",
    percentualmargemDisponivelCartao: 0,
    percentualMargemTotalCartao: 0,
    margemDisponivelRcc: 0,
    margemDisponivelEmprestimoOn: "N/D",
  },
};
