import { EmpréstimoConsignadoValues } from "../Types";

export const initialValuesForm: EmpréstimoConsignadoValues = {
  beneficio: "0103097123",
  nome: "SEBASTIAO RIBEIRO",
  dataNascimento: "1956-09-04",
  cpf: "67418371080",
  situacaoBeneficio: "ATIVO",
  nit: "23524523",
  identidade: 0,
  sexo: "MASCULINO",
  dib: "2003-05-28",
  valorBeneficio: 0,
  possuiRepresentanteLegalProcurador: "Não",
  pensaoAlimenticia: "Não",
  bloqueioEmprestismo: "Não",
  beneficioPermiteEmprestimo: "Sim",
  naoPerturbe: "0",
  rg: "4232342",
  ddb: "2003-10-24",
  nomeMae: "CLARICE BAPTISTA RIBEIRO",
  descontosCartao: {},
  enderecoPessoal: {
    bairro: "N/D",
    cep: "N/D",
    cidade: "N/D",
    endereco: "N/D",
    uf: "N/D",
  },
  especie: {
    codigo: "32",
    descricao: "APOSENTADORIA POR INVALIDEZ PREVIDENCIARIA",
  },
  margem: {
    competencia: "02/2023",
    baseCalculoMargemConsignavel: 4101.43,
    margemDisponivelEmprestimo: 0,
    margemDisponivelCartao: 0,
    percentualMargemDisponivelEmprestimo: 12,
    percentualMargemTotalEmprestimo: 35,
    quantidadeEmprestimo: 9,
    possuiCartao: "Sim",
    percentualmargemDisponivelCartao: 0,
    percentualMargemTotalCartao: 0,
    margemDisponivelRcc: 0,
    margemDisponivelEmprestimoOn: "N/D",
  },
  // contratosEmprestimo: [
  //   {
  //     contrato: "",
  //     dataInicioContrato: "",
  //     competenciaInicioDesconto: "",
  //     competenciaFimDesconto: "",
  //     dataInclusao: "",
  //     situacao: "",
  //     excluidoAps: "",
  //     excluidoBanco: "",
  //     valorEmprestado: 0,
  //     valorParcela: 0,
  //     quantidadeParcelas: 0,
  //     quantidadeParcelasEmAberto: 0,
  //     saldoQuitacao: 0,
  //     taxa: 0,
  //     tipoEmprestimo: {
  //       codigo: "",
  //       descricao: "",
  //     },
  //     banco: {
  //       codigo: "",
  //       nome: "",
  //     },
  //   },
  // ],
};
